version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: tasklist_postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Boyilani10*
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  tasklist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasklist_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Boyilani10*
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata:
