name: Build, Dockerize, and Deploy Tasklist App

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - run: mvn clean package
      - run: mvn test

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tasklist-app:latest .
      - run: docker tag tasklist-app:latest ${{ secrets.DOCKER_USERNAME }}/tasklist-app:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/tasklist-app:latest

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd /home/sisonke/tasklist
            git reset --hard
            git pull origin dev
            mvn clean package
            sudo systemctl restart tasklist_app.service
